C2SM/spack-c2sm

packages/cosmo/package.py
Should work once PR [cosmo#262](https://github.com/COSMO-ORG/cosmo/pull/262) is merged, but shoud anyway not affect the cosmo installation and testing.
=> ADD: set env REAL_TYPE before submitting tests

packages/claw/package.py
@lxavier we could easily hack this feature to test the new branch?
=> ADD: claw build variant with omni-compiler master

packages/cosmo-dycore/package.py, packages/cosmo/package.py, sysconfigs/tsa_rh7.7/packages.yaml
Add threads to serialization to speed up the creation of the serialization data.
=> Thread serialization

packages/cosmo/package.py
launch jenkins cosmo@dev-build%pgi
=> Tests on scratch

config.py, sysconfigs/config.yaml
I've just realised the admin installations were not done under /project anymore, this PR aims to  fix that. It however keeps the modules and stages installations under scratch.
=> Project install

packages/icondusk-e2e/package.py
Fix for this issue
https://github.com/spack/spack/issues/4261#issuecomment-466005631
=> fix or hack to solve issue with rpath

tools/spack-scripting/scripting/cmd/devbuildcosmo.py
Fixes the problem with the +gt1 variant not being passed to the dycore.
=> Devbuildcosmo for mch

packages/xcodeml-tools/package.py
**This request cannot be merged before https://github.com/MeteoSwiss-APN/xcodeml-tools/pull/8**
=> Fix libxxml2 discovery in xcodeml tools

packages/serialbox/package.py
Fixes serialbox -> netcdf dependency.
=> Fix serialbox netcdf dependency

packages/claw/package.py, packages/xcodeml-tools/package.py
Additionally switched xcodeml-tools's repository
=> Added support for Claw v2.1-rc

packages/claw/package.py, packages/xcodeml-tools/package.py, sysconfigs/tsa/packages.yaml
Reverts MeteoSwiss-APN/spack-mch#110
=> Revert "Added support for Claw v2.1-rc"

config.py, packages/cosmo/package.py, packages/int2lm/package.py, sysconfigs/daint/config.yaml, sysconfigs/daint/packages.yaml, sysconfigs/tsa/config.yaml, sysconfigs/tsa/packages.yaml
Reverts MeteoSwiss-APN/spack-mch#148
=> Revert "FIX: v0.16.0"

packages/cosmo/package.py
set to lib64 instead of lib for version after 2.19.0
=> fix ecccodes lib dir in cosmo package

config.py
This fixes and issue where it was possible to set relative paths in spack config files through the `config.py` script.
When `cd`ing into a different directory, spack would then recreate all these folders again (e.g., spack stages, install directories etc).
=> Fixed relative paths in spack configs

packages/cosmo/package.py
The package was not working anymore with older version
=> Add switch for claw version prior to 2.1

docs/QuickStart.rst
=> Add documentation on how to run ICON on Tsa

.github/workflows/pull_request.yml
Just to test if upgrade of the sphinx version fixes the problem
=> [GitHub-Action]: Use own fork of sphinx-action

Jenkinsfile, test_spack.py
Adds a Python test file which does all the logic and a Jenkins file which forwards the GitHub comments to it.
There is now  a new Jenkins plan called PR_test2 which is labeled below as ''Jenkins MeteoSwiss-APN spack_PR new '. Once everything works, the old Jenkins plan can be deleted.
The wiki has been adapted.
=> PR testing

sysconfigs/daint/compilers.yaml, sysconfigs/daint/packages.yaml, sysconfigs/dom/compilers.yaml, sysconfigs/dom/packages.yaml
Cleanup the messy yaml-files for Daint.
Move towards a more minimal config for Spack by not specifying every tiny difference in the spec of the packages.
=> [Daint] cleanup config

test_spack.py
Adds the tests that the cosmo dycore team use for PR testing. https://jenkins-mch.cscs.ch/job/dycore_PR/
=> Adds cosmo dycore tests.

sysconfigs/tsa/compilers.yaml
This reverts commit 92ab7f68c4adc1039f5c31a2ff7b0f65f3f64039.
=> Revert "Removes 'CSCS_APPS_PATH'. (#422)"

packages/claw/package.py, sysconfigs/tsa/packages.yaml
Changes needed to make CI on Dom possible:
https://c2sm.github.io/spack-c2sm/Install.html#spack-instance-on-dom
=> [Claw] remove %gcc

docs/Install.rst
I found some remnants of the past in the install documentation
=> change old name spack-mch to spack-c2sm

test_spack.py
Restricts execution of IconTests to Daint.
Eliminates dead test code.
=> Removes ICON tests on Tsa.

packages/cosmo-dycore/package.py, packages/cosmo/package.py, packages/icon/package.py
Makes use of f-strings.
Sticks closer to [Sergey's Icon package](https://gitlab.dkrz.de/icon-spack/packages/-/blob/master/packages/icon/package.py).
=> Refactoring

README.md, create_new_sysconfig.sh, docs/QuickStart.rst, env-setup/load_python.sh, env-setup/machine.sh, install_sysconfig.py, packages/cosmo-dycore/package.py, packages/cosmo/package.py, packages/icon/package.py, packages/icontools/package.py, packages/int2lm/package.py, setup-env.sh, sysconfigs/balfrin/compilers.yaml, sysconfigs/balfrin/config.yaml, sysconfigs/balfrin/packages.yaml, sysconfigs/balfrin/upstreams.yaml, sysconfigs/daint/config.yaml, sysconfigs/daint/packages.yaml, sysconfigs/dom/config.yaml, sysconfigs/manali/config.yaml, sysconfigs/tsa/config.yaml, test_spack.py, tools/spack-scripting/scripting/cmd/devbuildcosmo.py, tools/spack-scripting/scripting/cmd/installcosmo.py
Note that this PR updates the branch **fdb_update**.
Updates the branch with latest developments of dev_v0.18.1, in case you're interested. No problem if you're not.
You can now "source" spack with `. spack-c2sm\setup-env.sh unknown` to force a "machine", in this case called _unknown_.
=> Fdb update

test/system_test.py
=> [Oasis] Test install

.github/workflows/preview.yml
See also https://github.com/C2SM/spack-c2sm/pull/616
=> Add PR preview action for v0.18.1

packages/eckit/package.py, packages/fckit/package.py, packages/infero/comment_out_log-level_info.patch, packages/infero/package.py, packages/tensorflowc/package.py, test/integration_test.py, test/system_test.py
Transfer Infero from 0.17.1 to 0.18.1
=> [0.18.1] Infero

packages/cosmo/package.py, packages/int2lm/package.py, sysconfigs/daint/compilers.yaml
Fixes https://github.com/C2SM/spack-c2sm/issues/579
=> [Daint] Move fix for missing linked libs from packages to sysconfig/daint/compilers.yaml

packages/icon/package.py, packages/infero/package.py
Last missing piece for c2sm users of ICON.
=> [Icon] Add variant for Infero

docs/QuickStart.rst
See https://github.com/C2SM/icon/tree/main/config/cscs/spack/v0.18.1.1/daint_cpu_nvhpc
=> [docs] Use correct path for spack.yaml file

packages/icon/package.py, test/system_test.py
Remove cdo as a dependency of icon.
Test a tag instead of a branch for icon.
=> [Icon] remove cdo as dep

packages/oasis/package.py
Solve the conflict between the MCT library used in CESM and the one used in OASIS.
=> Fix oasis mct

README.md, docs/QuickStart.rst, docs/Testing.rst, sysconfigs/daint/upstreams.yaml, test/unit_test.py, upstreams/daint/base/spack.yaml, upstreams/daint/icon-dsl/spack.yaml, upstreams/daint/icon-rttov/spack.yaml
Last PR before new release v0.18.1.4!
=> bump version to v0.18.1.4

README.md, docs/QuickStart.rst, docs/Testing.rst, docs/UpstreamManagement.rst
No need to run any test, because this only changes documentation.
=> [doc] Version bump

test/system_test.py
Test out-of-source builds for ICON.
Add a cce test because BB relies on that.
=> [ICON] add cce test, build out-of-source

repos/c2sm/packages/icon/package.py, test/system_test.py
The icon daint tests rely on +grib2. So I patched the spack environments.
=> [icon] Adds mpi-gpu, testbed and fixes defaults.

repos/c2sm/packages/icon/package.py
Add realloc-buff variant for icon : this is a gpu optimization to use (re)-allocatable buffer in the communication
=> [icon] Add variant realloc-buf

repos/c2sm/packages/fdb-fortran/package.py
=> fdb-fortran FDB dependency

docs/SpackChoice.rst
Based on an email sent to B. Cumming at CSCS.
=> [Docs] Target users of spack-c2sm

repos/c2sm/packages/cosmo/package.py, repos/c2sm/packages/flexpart-cosmo/package.py, repos/c2sm/packages/int2lm/package.py, test/system_test.py
Fixes https://github.com/C2SM/spack-c2sm/issues/873, https://github.com/C2SM/spack-c2sm/issues/869, https://github.com/C2SM/spack-c2sm/issues/863
=> Use tags for flexpart-cosmo, int2lm and cosmo tests

repos/c2sm/packages/cosmo-dycore/package.py, test/system_test.py
Fixes https://github.com/C2SM/spack-c2sm/issues/864
=> Add tag and maintainer for cosmo-dycore

repos/c2sm/packages/icon/package.py
Solves https://github.com/C2SM/spack-c2sm/issues/897
=> [Icon] conflict for gpu and loop-exchange

src/machine.sh, sysconfigs/euler/compilers.yaml, sysconfigs/euler/concretizer.yaml, sysconfigs/euler/config.yaml, sysconfigs/euler/packages.yaml, sysconfigs/euler/repos.yaml
Add Euler cluster with GCC 9.3.0
=> Add Euler Cluster

repos/c2sm/packages/cosmo-eccodes-definitions/package.py, repos/c2sm/packages/fdb-fortran/package.py
Closes https://github.com/C2SM/spack-c2sm/issues/865 and https://github.com/C2SM/spack-c2sm/issues/868
=> [cosmo-eccodes-definitions] [fdb-fortran] Update maintainers

sysconfigs/tasna/compilers.yaml, sysconfigs/tasna/packages.yaml, sysconfigs/tasna/upstreams.yaml
Copy of sysconfig/balfrin, but with all "balfrin" strings replaced by "tasna".
No test covers any of this, because we don't test on tasna.
=> [tasna] Update sysconfig to v6

repos/c2sm/packages/flexpart-cosmo/package.py
Fixes https://github.com/C2SM/spack-c2sm/issues/951
=> Use single-thread make for flexpart-cosmo

test/system_test.py
=> Remove split_phases

sysconfigs/balfrin/packages.yaml
OS changed. Created with `spack external find`.
=> [balfrin] Update packages

repos/c2sm/packages/py-gt4py/package.py, test/system_test.py
=> Revert "new gt4py tag"
