- packages/cosmo-dycore/package.py
It would be nice to be able to compile the dycore with performance meters using a variant
> add perf meter variant

- packages/gridtools/package.py
I think variants, also if booleans, need to be evaluated with spec['variant'].value
> fix evaluation of variants in gridtools

- packages/claw/package.py
- packages/cosmo-dycore/package.py
- packages/cosmo-grib-api/package.py
- packages/cosmo/package.py
- packages/gridtools/package.py
- sysconfigs/admin-daint/packages.yaml
- sysconfigs/admin-tsa/packages.yaml
- sysconfigs/daint/packages.yaml
- sysconfigs/tsa/packages.yaml
The proposal here is to explicitly force gcc on dependencies of packages that are purely C/C++, to avoid falling into pgi when trigger from a top level package that had Fortran and requested pgi. 
The dependencies coming from already C++ projects like dycore should not be a problem, since the dycore should itself be compiled with gcc, but I thought being explicit everywhere would anyhow be a good practice. 
The problem came from a system that didnt not contain jasper, which propagated C dependencies being compiled with pgi. In the end openssl failed to compile with pgi
What do you think?
```
cosmo@aws_5.07.mch1.0.p4%pgi@19.10~claw cosmo_target=cpu ~cppdycore~debug~eccodes+parallel~pollen real_type=double ~serialize slave=aws arch=linux-ubuntu18.04-skylake_avx512 …
```
> make explicit use of gcc for C projects

- packages/cosmo/package.py
I think in case of cpu, gridtools will always build with OpenMP. 
This will be incompatible with pgi Fortran cpu that ships a different openmp.
> add a conflict due to OpenMP

- packages/cosmo-dycore/package.py
- packages/cosmo/package.py
How about adding a production variant that will fix all options that are a must for producing a production executable, and avoid mistakes like compiling a production exe w/o claw?
> Add production variant

- README.md
- config.py
This PR aims to add an upstreams option to the config.py script. The option can be set to ON and OFF and allows the installation of a upstreams.yaml configuration file in the site scope of the installed spack instance.
> ADD: -u or --upstreams option

- packages/cosmo-dycore/package.py
- packages/gridtools/package.py
Remove the CudaPackage option for gridtools and dycore since it makes testing impossible.
> FIX: gridtools and dycore CudaPackage

- README.md
For development, most of the times you want to rebuild multiple times while the source code is changing. We need to add instructions for that, otherwise spack will not re-build once installed
> extend instructions of the readme for dev-build

- README.md
* Stripped trailing whitespaces.
* removed mixed tabs & spaces: tabs -> 2 spaces
* Removed `$` prefix in code blocks, so users can easily copy & paste multi-line code blocks.
* Changed inline code blocks from indentation to three back ticks as suggested by github's markdown guide: https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code
* Added bash annotation to code blocks for syntax highlighting.
* Replaced html lists with markdown list
> Minor changes to README.md's markdown

- packages/cosmo/package.py
This is in order to be able to get and build releases of MeteoSwiss-APN even if they are not specified as versions of the package. 
You can test it with 
```spack versions cosmo
==> Safe versions (already checksummed):
master          5.07.mch1.0.p3  5.06   5.05
5.07.mch1.0.p4  5.07.mch1.0.p2  5.05a  mch
==> Remote versions (not yet checksummed):
5.07.mch1.0.p5
```
right now, you wont see any remote version, because all of the auto-detected versions are also specified as safe versions. 
However if you remove 
https://github.com/MeteoSwiss-APN/spack-mch/blob/6f24ed493c632c02863fc1ddb713345792e41671/packages/cosmo/package.py#L20
you will see that 5.07.mch1.0.p5 is still auto detected. 
I think this is essential for building new releases with jenkins without having to push into master of …
> specify url to detect remote versions of cosmo

- packages/cosmo/package.py
* Removed trailing whitespace
* Removed conflict between `+serialize` and `+parallel`
Currently the bash scripts build cosmo serialization in parallel mode. All jenkins plans also build cosmo serialization in parallel mode.
If cosmo serialization isn't built with parallel mode, it doesn't support async IO and isn't MPI aware -> crashes with:
```
Working with reference atmosphere:             2
CLOSING apix FILE
*------------------------------------------------------------*
*    PROGRAM TERMINATED BECAUSE OF ERRORS DETECTED
*              IN ROUTINE:   global_vectorreal
*
*    ERROR CODE is            -1
*    MPI not available
*------------------------------------------------------------*
```
Not sure if the MPI error can be fixed with a namelist parameter or otherwise.
Nevertheless, it …
> Removed serialize-parallel conflict from cosmo

- packages/cosmo/package.py
Avoid the problem that master may be installed in the upstream.
Usage : spack dev-build --until build cosmo@dev-build%pgi cosmo_target=cpu -cppdycore
> Add a new version dev-build, for dev-build compilation

- packages/claw/package.py
Otherwise build fails because `flex` is not found.
> add claw->flex dependency

- packages/cosmo-dycore/package.py
- packages/cosmo/package.py
- sysconfigs/daint/packages.yaml
- sysconfigs/tsa/packages.yaml
This makes sure that cosmo%pgi will take the right dycore if the corresponding dycore is installed with ^openmpi%pgi
> FIX: gnu compiler for cuda and slurm

- .gitignore
- packages/dawn/package.py
To install python stuff need to depend on `py-setuptools` and `py-protobuf`.
Also sneaked in: git ignore of spack installation in folder `spack` under root (annoying when preparing commits).
> Fix dawn package.py

- packages/cosmo-dycore/package.py
I actually broke this myself. In https://github.com/COSMO-ORG/cosmo/pull/319 I changed the _interface_ of the testtool. This updates the `cosmo-dycore` package so it works with the changes.
> Removed buggy & optional datapath

- packages/dusk/package.py
- packages/icondusk-e2e/package.py
I think it's better if `icondusk-e2e` uses a fixed commit from `dusk`. However, I think it'll break the `icondusk-e2e_PR` jenkins plan, since that plan works only if `icondusk-e2e` can use _any_ version of `dusk`.
> Added dusk version with fixed commit for icondusk

- packages/icondusk-e2e/package.py
It became uncompatible with `dusk` which depends on the `3.8.x` version range of python. Fixing by depending on the same version range.
> Fix icondusk-e2e's direct dependency on python

- packages/dawn4py/package.py
`dawn4py` depends on `black` and `pytest` (listed as REQUIRED in its `setup.py`). Spack is not very consistent in how it resolves the dependencies defined in the `setup.py` of the package.
In this case, running `dusk` from command line, triggered `pkg_resources.DistributionNotFound` errors for both dawn4py's dependencies.
Solvable by replicating the dependency connection here in the `package.py` of dawn4py.
> Add dawn4py's dependencies to its package.py

- config.py
- packages/cosmo/package.py
- packages/int2lm/package.py
- sysconfigs/daint/config.yaml
- sysconfigs/daint/packages.yaml
- sysconfigs/tsa/config.yaml
- sysconfigs/tsa/packages.yaml
The changes are structural changes because of the new version. The config content does not change.
Main structural changes: 
config.py:  'install_tree' goes to install_tree: root:
packages.py: paths is replaced by externals:  - spec: <spec> -prefix: <path>
Packages changes:
netcdf-fortran does not provide the +mpi variant anymore
> FIX: v0.16.0

- packages/int2lm-org/package.py
Similar to #159 but for int2lm-org
> FIX: switch to /lib64 for eccode version >= 2.19.0

- packages/int2lm-org/package.py
- packages/int2lm/package.py
Avoid having libgrib1 in run-env
> Set dependecy type for all int2lm dependecy

- packages/cosmo/package.py
This allow mch to build releases, but C2SM will not work anymore - this is a temporary solution
> Fix for MCH release

- config.py
Technical description: 
==================
it includes several modifications in order to eliminate error prone behaviour. 
* If the specified reposdir (or default) does not exits throw an exception instead of silently ignoring the user choice.
* If args.reposdir + '/repos.yaml' already exists, replace it anyway. It is expected that config.py will create a new installation overwrite previous installations.
* For all the various configurations, do not modify the source of spack-mch, but rather the installed instances
* replace all os.system with subprocess.run(..., check=True) so that a failure will throw an exception
* replace a greedy `cp -rf * ` by explicit requirement of copies
* PEP8 formatting
* python2 -> python3 (required by subprocess.run)
Testing:
=======
Tested with 
``` …
```
> Improved behaviour of config for spack installation

- packages/cosmo/package.py
Install the spack build env, in order to avoid having to find it in the stage path when deploying the install
> install build env

- packages/cosmo/package.py
This cause an error as package.env_path is incorrect in case of a devbuild, as it looks for the file in stage
Fix the dev-build command and the cosmo_PR plan in jenkins which is currently broken
> Do not install env in case of devbuild

- packages/cosmo-dycore/package.py
- packages/cosmo/package.py
The name of the cosmo repository changed in C2SM-RCM, so this PR will fix the path in the Spack installation.
> Change C2SM repository path

- packages/cosmo/package.py
This is passed to the Makefile. It is needed since when re-installing an existing version Spack uses a cached version of the source code which has no git information. In such case the internal version mechanism of the cosmo build does not work.
> add set_version variant to cosmo

- packages/cosmo-dycore/package.py
- packages/cosmo/package.py
- sysconfigs/daint/packages.yaml
- sysconfigs/tsa/packages.yaml
The use of multi-value variants of spack for slurm_args triggered errors with the spack uninstall, location, find,... 
Therefore we need to revert this to use individual variants for each of the slurm parameters
goes together with this: 
https://github.com/COSMO-ORG/cosmo/pull/393
> Revert multi value

- packages/serialbox/package.py
Since serialbox has a public repo, we can just use the https url.
This way, no working ssh key is required to connect to git.
> Changed serialbox git url to https

- packages/cosmo/package.py
The default versions of this dependecies is controlled in the cosmo repo in the cosmo/ACC/spack/spec.yaml
> Remove version of serialbox and claw in cosmo

- packages/dusk/package.py
We discussed that we don't want this version anymore. icondusk-e2e will use the default version (currently `horizon`) and we have to maintain a single version of dusk for both ICON and icondusk-e2e.
> Removed obsolte icondusk-e2e version from dusk

- docs/SpackCommands.rst
- packages/cosmo/package.py
- packages/zlib_ng/package.py
This change speeds-up the work done in this PR:
https://github.com/COSMO-ORG/cosmo/pull/405
Using the zlib_nb is about 2x faster the the original zlib.
Making zlib_ng a link-dependency did not work, ldd cosmo still pointed to the systems zlib.
Therefore I went for the run_environment set in zlib_ng package itself.
> new variant +zlib_ng for cosmo to allow much faster compression of NetCDF output

- packages/cosmo/package.py
When fetching versions of cosmo repositories, a confusing git error
message (like fatal ERROR) appears for repos to which the user doesn't
have access. Replace it with a more useful warning.
> Replace git error message when fetching cosmo versions

- sysconfigs/daint/compilers.yaml
- sysconfigs/daint/packages.yaml
Similarly to https://github.com/C2SM/spack-c2sm/pull/265, the compiler and packages settings have to be adapted for Piz Daint after the upgrade from 9-10 September 2021.
> Update compilers and packages for daint

- sysconfigs/daint/compilers.yaml
- sysconfigs/daint/packages.yaml
Since ICON buildbot is soon going to take cce@12.0.2 as default (2.6.5-rc), I'd like to upgrade our default cray compiler on Daint to point to the same version. Following the discussion on not keeping too many compilers, this PR also get rid of the oldest cray compiler version (cce@10.0.2).
> ADD: cce 12.0.2 daint

- docs/Install.rst
- docs/SpackCommands.rst
The following error can occur if the cache of the spack installation is somehow broken. Since the error message doesn't point to anything useful, it might be worth to address this in the documentation.
```
spack installcosmo -v cosmo@master%pgi
==> Error: 'str' object has no attribute 'get'
```
> [docs] Add fix to docs for `spack install` error

- tools/version_detection.py
This warning caused issues in icon https://github.com/C2SM/spack-c2sm/issues/394.
The idea to warn is good but it creates problems, so it's better to remove the warnings for now.
I don't think this needs any Jenkins testing. Formal review should be sufficient.
> Removes warning if version detection can't access repo.

- packages/icon/package.py
Needed by Will Sawyer to test the new cray compiler for ICON & GPU target
> FIX: enable cce gpu for ICON

- tools/spack-scripting/scripting/cmd/devbuildcosmo.py
For some reason the function custom_devbuild changes args also outside the function. Thus, if the function is called twice, args.things_to_test was no longer one of the options and was therefore set to false. The function was called twice when running spack devbuildcosmo with cppdycore (+cppdycore), which is why the testsuite wasn't run.
> Bugfix: tests didn't run with cppdycore

- packages/cosmo/package.py
Adds env variables if 'libaec' is in the specs.
It would be nicer to add this to eccodes but that doesn't work. So this is the best way I was able to make it work.
> Adds aec support to cosmo

- Jenkinsfile
- docs/PrTesting.rst
- test_spack.py
This PR addresses https://github.com/C2SM/spack-c2sm/issues/420.
Developer's to-do:
**Technical description of changes:**
Adds `class TestCase(unittest.TestCase)` in between test-classes and the unittest framework, to provide functions `Run` and `Srun` so each test-calss' package name and method name can be accessed. (Because the method name goes into the log file name) This replaces the free function `run`.
Adds `class CustomTestSuite(unittest.TestSuite)` which is able to run tests in parallel. Shamelessly copied from StackOverflow.
Adds a variable `machine_count`, which counts how many machines are passed as arguments. If multiple occur, execution is halted, because the user specified an explicit machine. Specifying multiple machines is not supported at the moment.
Adds `--tsa` and …
> Srun one level down

- config.py
It makes more sense to me to install version_detection even if a "spack" folder is already present.
Only the cloning of the spack repo should be skipped
> install version-detection even in spack is present

- packages/icon/package.py
Introduce `+proper-netcdf-dep` so that:
- people with unpatched ICON wrappers can still build without changing their ICON source - no action required
- people with the latest wrapper can build aswell but have to add the `+proper-netcdf-dep` variant to the spack call.
How I think merging this will work:
1. merge this change into spack-c2sm:master
2. wait until spack instance is updated
3. verify buildbot passes all tests with ICON MR (https://gitlab.dkrz.de/icon/icon-nwp/-/merge_requests/426)
4. merge on ICON-side
5. after X amount of time: remove `proper-netcdf-dep` variant to enforce proper netcdf dependency
> Icon transit

- packages/cosmo-dycore/package.py
- packages/cosmo/package.py
Empa uses a modified version of COSMO (with greenhouse-gas tracers): https://github.com/C2SM-RCM/cosmo-ghg
This should be build with spack now. Additionally, I tried to change the name of the executable to `cosmo-ghg` to avoid confusion with standard `cosmo`. However, it doesn't work at the moment and there is some duplication of code.
> [Cosmo] Add cosmo-ghg version

- docs/SpackCommands.rst
- sysconfigs/daint/config.yaml
- sysconfigs/dom/config.yaml
- sysconfigs/tsa/config.yaml
- test_spack.py
- tools/spack-scripting/scripting/cmd/devbuildcosmo.py
- tools/spack-scripting/scripting/cmd/installcosmo.py
Currently we do not execute any tests for some packages because Spack
does not run test if a package is already installed:
```python
self.Srun(
'spack install cosmo-dycore@master%gcc real_type=float build_type=Release +cuda'
)
self.Run(
'spack install --test=root cosmo-dycore@master%gcc real_type=float build_type=Release +cuda'
```
In order to still test something we need to do as follows:
```python
self.Srun(
'spack install --until build cosmo-dycore@master%gcc real_type=float build_type=Release ~cuda'
)
self.Run(
'spack install --dont-restage --test=root cosmo-dycore@master%gcc real_type=float build_type=Release ~cuda'
)
```
This PR implements:
- Split build and test into two phases
- Build on compute nodes
- Run tests on Login-Nodes
- Use srun on Piz Daint too
- Randomly delay (5-20s) …
> [Test] Split build and test into two parts

- tools/spack-scripting/scripting/cmd/devbuildcosmo.py
The custom command devbuildcosmo always serializes data if `+serialize` is set.
This is counterintuitive, since for installcosmo there is no such thing in place.
Additionally, it missed the `--spec`argument, therefore it broken anyway and not used by anyone.
We manually call the script in our Jenkins-Plan:
```bash
spack load $SPACK_SPEC
./cosmo/ACC/test/tools/serialize_cosmo.py -s "$SPACK_SPEC" -b "."
```
> [devbuildcosmo] Remove broken mechanism to serialize data

- packages/claw/package.py
- packages/cosmo-dycore/package.py
- packages/cosmo/package.py
- packages/eccodes/package.py
- packages/gridtools/package.py
- packages/icon/package.py
- packages/serialbox/nag/examples.patch
- packages/serialbox/nag/ftg.patch
- packages/serialbox/nag/interface.patch
- packages/serialbox/package.py
- packages/serialbox/ppser_py3.patch
- sysconfigs/daint/packages.yaml
- sysconfigs/templates/daint/packages.yaml
- sysconfigs/templates/dom/packages.yaml
- sysconfigs/tsa/packages.yaml
Repace our current serialbox-package with the one provided by Sergey in Spack.
This change allow to get rid of all hardcoded `cmake%gcc`!
Nonetheless the following modifications with regard to the original implementation were applied:
- Add `cmake_flags.append('-D__GCC_ATOMIC_TEST_AND_SET_TRUEVAL=1')` to flaghandler to account for Daint specialities
- Remove Python as run-dependency (tried to rebuild Python during build)
- Hardcode boost dependency to `depends_on('boost@1.67.0%gcc', type='build')`to avoid a rebuild
This piece of works serves as an sub-step to fully outsource serialbox to the official Spack distribution
**To-Do**
> [Serialbox] Import "official" package from Sergey

- sysconfigs/tsa/compilers.yaml
Fix colon in tsa compilers. 
I dont know what the consequences this change might trigger, since I dont know if the previous yaml was compliant and accepted by syntax
> [Tsa] fix typo in compilers

- packages/icon/package.py
This MR adds a `+mixed-precision` option to the `icon` package.
> add variant for icon mixed-precision

- packages/cosmo-dycore/package.py
- packages/cosmo/package.py
- packages/icon/package.py
- packages/icontools/package.py
- packages/int2lm/package.py
By removing the values, any host/slave can be used and the list doesn't require maintenance anymore.
A missing host/slave value can be caught earlier. Potentially when loading config files in ICON. Till now the default value could have caused undesirably long continuation with a bad config.
> Sets default host/slave to 'none' and removes values.

- packages/int2lm/package.py
- test_spack.py
Advertise the c2sm branch, such that it does not require dev-build.
Depends on: Rename the branch in the C2SM-RCM/int2lm repo from `c2sm` to `c2sm-features` to mirror the cosmo naming scheme.
> Int2lm: Advertise c2sm-features branch

- test_spack.py
Added the function spack_install_and_test, which automatically checks if 'spack devbuildcosmo', 'spack installcosmo' or 'spack install' should be used and calls self.Srun and self.Run with the same arguments as before.
> Remove code duplication in test_spack.py

- packages/icontools/package.py
`eccodes` is not a variant of icontools
> [icontools] Removes dead code

- send_summary_as_comment_to_PR.py
- test_spack.py
Makes use of `str.endswith(..)`.
Provides extensible list of trigger phrases that cause 🟡.
> Moves all failure analysis logic from test_spack.py to send_summary_as_comment_to_PR.py

- send_summary_as_comment_to_PR.py
Running `launch jenkins --daint infero` makes the builder of Tsa fail, because the GitHub API does not accept an emtpy string as message. Therefore send a meaningful message instead.
> [CI] send dummy message if no test executed on a node

- packages/icon/package.py
Allows to specify where to look for "externals/atm_phy_echam_submodels/namelists" via setting the config_dir variant.
> [icon] Fix hammoz nml path

- packages/eccodes/package.py
Version 2.19.0 is not available as checksummed version in official package.
Therefore Spack used to ask if unsafe version can be fetched. This fails for non-interactive sessions
like pipelines.
> [eccodes] add  version 2.19.0

- .gitignore
- Jenkinsfile
- packages/cosmo/package.py
- packages/int2lm/package.py
- src/__init__.py
- src/report_tests.py
- src/spack_commands.py
- sysconfigs/balfrin/config.yaml
- sysconfigs/daint/config.yaml
- sysconfigs/dom/config.yaml
- sysconfigs/tsa/config.yaml
- sysconfigs/tsa/packages.yaml
- sysconfigs/unknown/config.yaml
- test/integration_test.py
- test/system_test.py
Localizes 'test_stage' and 'misc_cache'.
Adds Jenkins stage 'Bootstrap spack' to mitigate race condition on it.
[tsa] Removes nvhpc from packages:all:compiler.
[int2lm] Changes dependency on libgrib1@master to libgrib@22-01-2020. They are the same commit ATM.
Refactoring of spack_commands.py, integration_test.py and 'spack_install_and_test(..)'
Improves test reports.
Removes 'srun' for Balfrin to avoid Spack locking problems.
Adds patches for cosmo @6.0
Adds tests for
- cosmo @6.0 (install and dev-build)
- cosmo @5.09a.mch1.2.p2
- cosmo-dycore @6.0
- gridtools @1.1.3 %nvidia_compiler
- int2lm @int2lm-3.00 %gcc
- int2lm @int2lm-3.00 %nvidia_compiler
- zlib_ng @2.0.0
Deactivates failing tests.
> [test] Adds more tests

- sysconfigs/daint/config.yaml
With regard to upstream I think it makes sense to inlcude the compiler version in the prefix.
To maintain the same depth of the install-tree, I merged package.name and package.version into the same level.
> [Daint] Include compiler version in install path

- .github/workflows/deploy_docs_to_latest.yml
- .github/workflows/deploy_docs_to_tag.yml
Push docs present in master/main branch here:
https://c2sm.github.io/spack-c2sm/latest/
Push docs for a tag (i.e 99.99) here:
https://c2sm.github.io/spack-c2sm/99.99
The action only works if the tag is created through the GitHub webpage as a release:
https://github.com/C2SM/spack-c2sm/releases
I anyway use to create tag through this interface.
> more actions for deployment of docs

- packages/cosmo-dycore/package.py
Otherwise spack fails complaining about a non-existing URL when compiling cosmo (the dycore gets installed properly): `==> Error: Can't extrapolate a URL for version dev-build because package cosmo-dycore defines no URLs`
> FIX: add URL to cosmo-dycore package

- packages/icon/package.py
- set `configure_directory` to git-root if different from `self.stage.source_path`
- sync input-files for experiment following closely what is done in configure-wrappers
- Skip configure-phase if file `icon.mk` already present and spec is identical to previous installs
- `make distclean` reset this behaviour, like you expect from build without Spack
> [Icon] Enable out-of-source builds, skip configure-phase if icon.mk already present

- packages/libxml2/package.py
- sysconfigs/tsa/packages.yaml
I dug a bit into libxml2.
Libxml2 never tested their software with pgi and de facto it doesn't work. (I tried several versions)
The versions of libxml2 in spack v0.18.1 are not compatible with `nvhpc @21.1:` because version 21.1 introduced something that broke compatibility. (A side effects from ["enabled via the compiler built-in type __float128"](https://docs.nvidia.com/hpc-sdk/archive/21.1/pdf/hpc-sdk211rn.pdf)) Newer versions of libxml2 are compatible with newer versions of nvhpc though.
I also removed `spec: libxml2@2.9.9` in Tsa's sysconfig, because IMHO not specifying the compiler, the package was build with, is just tricking spack into thinking it's a match, thus circumnavigating the logic of the concretizer. I think we shouldn't trick spack.
A valid argument against this PR is …
> [libxml2] Adds conflicts with nvidia compilers.

- Jenkinsfile
- src/__init__.py
- src/github.py
- src/report_tests.py
- test/integration_test.py
- test/system_test.py
- test/unit_test.py
This pull request is meant to solve the issue [Report tests in a table](https://github.com/C2SM/spack-c2sm/issues/568).
- The output is shown differently than suggested (see outcome of launch jenkins below). The advantage is that one can see the output earlier than at the end of all tests and it's much easier to program. (I deleted old jenkins output, so that's clear what the final output looks like)
- If all tests on one machine of, for example, the integration tests are green, the collapsible is green, if one of the tests is red, locked, wastebasket or hourglass, the collapsible is red. If all tests are either green our yellow, the collapsible is yellow.
- The commit [Adds HTML string formatting](https://github.com/C2SM/spack-c2sm/commit/df94049d465a154bca1770bbad6fd4a34e02d508) was …
> 568 report tests in a table

- packages/icon/package.py
- test/system_test.py
**Single fcgroup**:
`fcgroup=DACE;externals/dace_icon;-O1`
**Multiple fcgroup**:
`fcgroup=DACE;externals/dace_icon;-O1,OCEAN;ocean/src;-02`
The grammar of the variant is checked using regex. It needs to be
`GROUP_NAME;files;flags`, separated by `;`
Testrun in ICON using this branch was succesfull with the new dace experiment:
https://gitlab.dkrz.de/icon/icon-nwp/-/pipelines/31976
**Limitations**:
When defining flags, each group is only allowed to hold one value for flags, i.e `-O1`,
because whitespaces corrupt the spec-parsing later on.
_A solution could be to separate the flags with `:` as it is done for files (implemented in configure of icon)._ 
**Edit JJ: This is not so easy, since in yaml `:` has a meaning, basically messing up the yaml-structure.**
> [Icon] introduce generic variant for --enable-fcgroup

- repos/c2sm/packages/cosmo-eccodes-definitions/package.py
This enables ICON's buildbot to access cosmo-eccodes-definitions without any ssh credentials for GitHub.
> [cosmo-eccodes-definitions] Makes URLs https.

- docs/conf.py
Somehow since [version 0.18.1.4](https://c2sm.github.io/spack-c2sm/v0.18.1.4/QuickStart.html), the console input prompt `$` is being copied when clicking on the "copy" button within the docs.
It worked before, but we didn't explicitly set this in our `conf.py`. This PR solves this.
See https://sphinx-copybutton.readthedocs.io/en/latest/use.html#strip-and-configure-input-prompts-for-code-cells
> Strip and configure input prompts for code cells

- repos/c2sm/packages/cosmo-eccodes-definitions/package.py
https://github.com/COSMO-ORG/eccodes-cosmo-resources/blob/v2.19.0.7/samples/RELEASE is a symlink that points to `../RELEASE`, thus https://github.com/COSMO-ORG/eccodes-cosmo-resources/blob/v2.19.0.7/RELEASE should be installed as well.
> [cosmo-eccodes-definitions] Install additional file.

- repos/c2sm/packages/icon/package.py
The need for `async-io-rma` stems from https://gitlab.dkrz.de/icon/icon-nwp/-/merge_requests/807
The need for `cuda-graphs` stems from https://gitlab.dkrz.de/icon/icon-nwp/-/merge_requests/716
> [icon] Adds variant async-io-rma and cuda-graphs.

- README.md
- docs/QuickStart.rst
- docs/Testing.rst
- sysconfigs/daint/upstreams.yaml
- test/unit_test.py
- upstreams/daint/base/spack.yaml
- upstreams/daint/icon-dsl/spack.yaml
- upstreams/daint/icon-rttov/spack.yaml
For ICON's BB on Balfrin, MCH would like to test `icon ~async-io-rma`. Thus we need a new version.
@jonasjucker @mjaehn If this is okay with you, I'd merge and create the new release.
> Version bump to v0.18.1.5

- upstreams/daint/icon-dsl/spack.yaml
Requires a new installation of the upstream "icon-dsl"
This happens when new release is published
> [Upstream] include icon4py@0.0.4

- repos/c2sm/packages/icon/package.py
https://gitlab.dkrz.de/icon/icon/-/commit/94ef9cb5b76cdfdda6e8b8c2a6b3d872c41104b8
has been merged in rc of ICON.
Therefore we can remove the patch.
> [Icon] remove patch for cce

- repos/c2sm/packages/icon/package.py
This is needed for externals built with CMake, as implemented here:
https://gitlab.dkrz.de/icon/icon-mpim/-/merge_requests/145
> [Icon] make CMake a build dependency

- repos/c2sm/packages/icon/package.py
This PR is a step toward a recipe that does not manipulate files/configs implictitly.
> [Icon] Remove implicit downgrade of opt-level in icon.mk.in

- repos/c2sm/packages/cosmo-eccodes-definitions/package.py
I didn't add a test for the new version because an other branch is currently modifying the system tests. More tests need to be added systematically later on anyways.
> [cosmo-eccodes-definitions] Adds 2.25.0.2

- repos/c2sm/packages/py-gt4py/package.py
- test/system_test.py
New version (living in c2sm-fork) before introduction of Dace backend for next, that will requires some API-change in the package.
> [gt4py] add version 1.1.2 from c2sm-fork

- repos/c2sm/packages/icon/package.py
The variant "gpu" follows closer the configure of icon.
This change is required to use --enable-gpu=openacc for the configure script in ICON
> [icon] Adds variant 'gpu'

- sysconfigs/copy_alps_env_files_from.sh
Useful for updating or using with squashfs and `/mch-environment/devt`.
Intended use: `./sysconfigs/copy_alps_env_files_from.sh /mch-environment/v8`
> Adds bash script to copy the files from alp's environment.

- repos/c2sm/packages/icon/package.py
Icon `depends_on('libfyaml', when='+coupling')` but consumed libfyaml also if `+art`.
> [icon] Bugfix for +art ~coupling.

- repos/c2sm/packages/icon/package.py
Like that the information about test failed or passed is at the end of the log-file.
> [icon] move call to test.py after install-phase

- repos/c2sm/packages/icon-ham/package.py
This fix by @dominichofer allows for out-of-source builds for the icon-ham package. The path to the namelists directory was pointing to the respective copy in the build folder (for out-of-source builds), however it should point to the original namelists directory at the icon root. To achieve this we join the absolute path with the `configure_directory` property.
> [icon-ham] Fix filepath to HAMMOZ namelists for out-of-source builds

- repos/c2sm/packages/icon/package.py
- repos/c2sm/packages/py-gt4py/package.py
- repos/c2sm/packages/py-icon4py/package.py
- test/system_test.py
Adapt the icon4py spack recipe to test the advection component. These changes are valid for icon4py releases higher than [v0.0.8](https://github.com/C2SM/icon4py/releases/tag/v0.0.8). The arguments ` '-m',  'not slow_tests'` are added to the `pytest ` command  to ignore the four slow advection stencils for the testing.
> [py-icon4py, icon] Modifications for merge of advection

- .vscode/settings.json
- sysconfigs/balfrin/concretizer.yaml
- sysconfigs/daint/concretizer.yaml
- sysconfigs/dom/concretizer.yaml
- sysconfigs/eiger/concretizer.yaml
- sysconfigs/tasna/concretizer.yaml
- sysconfigs/tsa/concretizer.yaml
- sysconfigs/unknown/concretizer.yaml
- test/conftest.py
Addresses https://github.com/C2SM/spack-c2sm/issues/843
Removes the value error if neither parallel nor serial testing is set, because local testing with VSCode doesn't have nor needs this separation.
Adapts the .vscode setting to the recent changes in VSCode.
> Sets concretizer:reuse:true for all sysconfigs

- repos/c2sm/packages/py-gt4py/package.py
- test/system_test.py
udpates to gt4py recipe: 
- new gt4py version 1.0.15
As for the `py-icon4py` package in order to reduce the dependencies of the `py-gt4py` package by reduceing  the tests being run to those relevant for `icon-dsl`: 
`gt4py` supports quite a few backends now: dace, gpu, gtfn, python but `icon-dsl` uses the `gtfn` backend for code generation through `icon4py`.
code coverage has been removed from the test run, it is relevant for `gt4py` development but not for spack packaging.
> Gt4py version 1015

- repos/c2sm/packages/flexpart-fdb/package.py
- repos/c2sm/packages/flexpart-opr/package.py
Replaces use of branches as reported here https://github.com/C2SM/spack-c2sm/issues/854
> Use tags for flexpart-opr and flexpart-fdb

- test/system_test.py
Simplifies problem hunting, when a spec concretizes differently in a user's spack instance and Jenkins' spack instance. This normally happens when users have preinstalled packages they are unaware of.
> Add spack spec to log

- repos/c2sm/packages/py-gt4py/package.py
- repos/c2sm/packages/py-icon4py/package.py
- test/system_test.py
We're only preserving versions of icon4py and gt4py that the users will need via icon-dsl. So far only one tag of icon-dsl exists, and another tag is in progress.  So only two tags of icon4py and gt4py each are retained.
> [py-icon4py,py-gt4py] Remove unused versions

- upstreams/daint/icon-dsl/spack.yaml
Trying to include most python dependencies that the upcoming icon-dsl tag will be able to use.
> Daint upstream for icon-dsl

- docs/QuickStart.rst
Users are still confused about which Spack tag they should use. This change was proposed here: https://github.com/C2SM/Tasks-Support/discussions/42
> Make clearer which SPACK_TAG to use

- repos/c2sm/packages/icon/package.py
Add variant acm-license for ICON
This is required for license reason and to be compatible with the latest ICON version
> Add acm-license variant for ICON

- repos/c2sm/packages/icon/package.py
- test/integration_test.py
Multi-value variant to inject any configure-argument not yet available as variant.
Ensure that format is either "--enable-arg" or "--disable-arg".
Solves https://github.com/C2SM/spack-c2sm/issues/890
> [ICON] add variant extra-configure-args

- repos/c2sm/packages/py-gt4py/package.py
- test/system_test.py
Need this version for the jenkins stable-gt4py tests for latest icon4py. A new icon4py tag will follow.
> [py-gt4py] Adding new gt4py v1.0.1.7

- repos/c2sm/packages/flexpart-cosmo/package.py
- repos/c2sm/packages/makedepf90/package.py
- test/integration_test.py
- test/system_test.py
Fixes https://github.com/C2SM/spack-c2sm/issues/889
@pirmink @ayanu 
I added the `makedepf90` package, which is now a dependency of `flexpart-cosmo`.
> Add makedepf90 package for flexpart-cosmo

- repos/c2sm/packages/makedepf90/package.py
Required during configure : https://salsa.debian.org/science-team/makedepf90/-/blob/debian/3.0.1-1/Makefile.def?ref_type=tags#L137
> Makedep90 add dependency autoconf

- repos/c2sm/packages/py-icon4py/package.py
Forgot to add this folder mapping for icon4py tag 0.0.10 when it was originally added. Only showed an error when we tried to build icon-dsl with this version of icon4py.
> [py-icon4py] Fixing folder mapping for v0.0.10

- repos/c2sm/packages/icon/package.py
A new variant 'comin' was created to allow the enabling of ComIn in icon (default is `False`).
--> Use `+comin` to enable ComIn in the spack recipe.
> Enabling support for ComIn in ICON

- docs/QuickStart.rst
The name of the file for the Spack tag has been changed from SPACK_TAG to SPACK_TAG_DAINT. We should update his in the example
> Use SPACK_TAG_DAINT in example

- .github/workflows/deploy_docs_to_latest.yml
- .github/workflows/deploy_docs_to_tag.yml
- .github/workflows/preview.yml
- docs/C2SMGuidelines.rst
- docs/CodeDevelopment.rst
- docs/Makefile
- docs/conf.py
- docs/requirements.txt
Fixes https://github.com/C2SM/spack-c2sm/issues/912
> Remove custom versions from dev-build

- repos/c2sm/packages/icon/package.py
- test/integration_test.py
- test/system_test.py
Replaces icon-2.6.6 with icon-2024.01-1.
Adds variants nwp, art-gpl and comin.
Removes variants edmf and claw.
Deactivates test for `icon @2024.1-1 %gcc` on daint because it fails.
Replaces test of `icon @nwp-master` with a test of the conditional dependencies of of icon.
> [icon] Update to version 2024.01

- repos/c2sm/packages/xpmem/package.py
- repos/c2sm/packages/xpmem/xpmem_v2.6.5-36.patch
- test/system_test.py
Since cray-mpich depends on xpmem this could have consequences for all MPI applications and libraries.
> Add workarounds for concretizer

- repos/c2sm/packages/oasis/package.py
- repos/c2sm/packages/oasis/patches/patch.PSMILE_add_timer_as_dep_of_string
PSMILE makefile has wrong object deps. Only shows up for GCC compiler, hence not an issue so far.
With moving COSMO and OASIS to Euler this error poped up.
```patch
diff --git a/lib/psmile/src/Makefile b/lib/psmile/src/Makefile                                                                    
index 50086e0d..94762839 100755                                                                                                   
--- a/lib/psmile/src/Makefile                                                                                                     
+++ b/lib/psmile/src/Makefile                                                                                                     
@@ -65,7 +65,7 @@ mod_oasis_mpi.o: mod_oasis_kinds.o mod_oasis_data.o mod_oasis_sys.o mod_oasis_ti …
```
> [Oasis] add patch to fix broken makefile in 4.0

- repos/c2sm/packages/int2lm/package.py
- repos/c2sm/packages/libgrib1/package.py
- test/system_test.py
Activate tests on Balfrin that are still needed for users on Euler to make sure the recipes keep working.
> Prepare Daint shutdown

- repos/c2sm/packages/icontools/package.py
To process data from DWD, which uses eccodes 2.25.0, MeteoSwiss needs to set that version of eccodes.
> Icontools: Remove version restriction of eccodes

- Jenkinsfile
- test/system_test.py
icon-nwp is set to v7 already for some time.
Should be desirable to be alligned with spack-c2sm as well
> use v7 on Balfrin

- repos/c2sm/packages/cosmo-eccodes-definitions/package.py
@petrabaumann I'm leaving MeteoSwiss. So this package needs a new maintainer. Are you willing to adopt it? Since you create new cosmo-eccodes-definitions, I think you would be a fit.
> cosmo-eccodes-definitions: Update maintainers

- repos/c2sm/packages/icontools/package.py
- test/system_test.py
Use more sophisticated recipe from Sergey that offers more variants.
> [Icontools] use package from Sergey
